### ISSUE TITLE
nikola theme command failure

### ISSUE THREAD

**Issue by githubgnulinux** [getnikola/nikola-themes#142]
What to check in the system for this command terminal output?

nikola theme -i base-jinja

ERROR: Nikola: Unknown command theme

**Comment by Kwpolska** [comment]
You’re using an outdated version of Nikola. Based on your previous posts, you are most likely using Nikola v7.6.4 as installed from Debian repositories (`apt-get install nikola`). The version is pretty ancient (Debian’s fault), and thus not supported.

Instead, we recommend using Python 3, `virtualenv` and installing with `pip` inside a virtualenv — that should get you Nikola v7.8.11, which is the latest version. A lot of things were fixed since August 2015 (which is when v7.6.4 was released).

**Comment by Kwpolska** [comment]
PS. (1) you can’t install `base-jinja` which is built-in, (2) this sends a request to `themes.getnikola.com`, which is behind CloudFlare, and you know the rest of the story.
