### ISSUE TITLE
Make it clear in your tutorials where the sources for various themes are

### ISSUE THREAD

**Issue by orblivion** [getnikola/nikola-themes#146]
Just a minor UX suggestion. This is from the perspective of someone who has never used a static site generator. Keep in mind that from my perspective, when I first tried initializing a Nikola site, I was confused as to why there were no template files generated along with everything else (I'm used to Django). Where is the layout coming from? That's how clueless I am (and others probably are) coming into this.

So I figured out that "themes" are what I want to look into if I want a custom layout, and I'm looking through your theming tutorial. Before diving into the tutorial it would be nice to get an idea of what the different theme sources looked like, just to get a sense of what I can do with them.

I see a big list of themes here: https://themes.getnikola.com/. Each item has various links (Author, templating system used, etc). Some of them don't have links to source (that I can find), including the first couple. For this reason I initially guessed that none of them would have such links, but then I saw the third one did have a link.

Perhaps put a Source link at the top of each one, by the author? If no link is available for whatever reason, perhaps just say so, just so a new visitor knows that other ones do have source available? (Though I don't know why source wouldn't be available if it's open source).

**Comment by Kwpolska** [comment]
> I was confused as to why there were no template files generated along with everything else (I'm used to Django). Where is the layout coming from? That's how clueless I am (and others probably are) coming into this.

The built-in themes are not copied to user sites by default, which lets us improve them without needing user intervention. You can use `nikola theme -c NAME` to copy a built-in template for editing or `nikola theme -n NAME --engine ENGINE --parent PARENT` to create a new theme. (The theming tutorial uses `theme -n`.)

Built-in themes can be found in site-packages, and we recommend template overrides or custom inheriting themes instead of editing site-packages files.

I added a source code link to themes that are not built-in. [(example)](https://themes.getnikola.com/v8/bootblog/)

If you have any specific suggestions on documentation changes, or any further questions, feel free to ask, or send pull requests to docs (in the main getnikola/nikola repo).

**Comment by orblivion** [comment]
Thanks!

BTW in my verbosity I think part of my point was sort of lost. I did not mean to ask you here and now why template files are not generated. Rather, I was just trying to explain my ignorant point of view, and why I wanted to see the source.
