### ISSUE TITLE
Facebook comments count not updated

### ISSUE THREAD

**Issue by sindhus** [getnikola/nikola-themes#87]
hi, I am using facebook for comments but I see these errors in console

![screen shot 2016-07-30 at 10 49 20 am](https://cloud.githubusercontent.com/assets/4291156/17268273/b0b50504-5643-11e6-9aef-b146de02c2b4.png)

which I think results in comments not getting registered with the comments count:

![screen shot 2016-07-30 at 10 55 10 am](https://cloud.githubusercontent.com/assets/4291156/17268285/2cb878e8-5644-11e6-99d7-cd3982f9414e.png)

**Comment by Kwpolska** [comment]
jQuery is required for that to work (that’s documented; see also: getnikola/nikola#639) and it must be loaded very early (before that script). If you want Facebook comments with comment counts, please modify your templates. We can’t do this for everyone because it’s better to load jQuery at the end of `<body>` in most cases.

**Comment by sindhus** [comment]
Thanks!
